name: Test 2
on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        description: "Flavor to be executed"
        required: true
        options:
          - Full
          - ITPro
          - Developers
      mechanism:
        type: choice
        description: 'Kind of deploy tool'     
        required: true
        options: 
        - Arm
        - Bicep
        - Terraform
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Always
        run: |
          echo "flavor selected: ${{ github.event.inputs.flavor }}"
      - name: Print Conditional
        if: github.event.inputs.flavor == 'Full'
        run: |
          echo "flavor selected: ${{ github.event.inputs.flavor }}"
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        if: github.event.inputs.flavor == 'Terraform'
        with:
          terraform_version: 1.0.11
