name: Test 2
on: 
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor to be executed'     
        required: true
        options: 
        - Full
        - ITPro
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "flavor selected: ${{ github.event.inputs.flavor }}"