name: Test 2
on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        description: "Flavor to be executed"
        required: true
        options:
          - Full
          - ITPro
          - Developers
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Always
        run: |
          echo "flavor selected: ${{ github.event.inputs.flavor }}"
      - name: Print Conditional      
        if: github.event.inputs.flavor == 'Full'
        run: |
          echo "flavor selected: ${{ github.event.inputs.flavor }}"
