name: Manual Execution with parameters
on: 
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor to be executed'     
        required: true
        default: 'Full'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "flavor selected: ${{ github.event.inputs.flavor }}"